title: Frank Blog
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Frank Bai # add your name
author-img: frank.png # add your photo
about-author: I'm a Full Stack developer, good at Android, Bash, Python, HTML. Love coding, Love Life. # add description
social-github: xixigeek # add your Github handle
social-linkedin: yinbai # add your Linkedin handle
social-email: byszy2008@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
